version: "3.1"

services:

  seata-server:
    image: seataio/seata-server:latest
    hostname: seata-server
    ports:
      - 8091:8091
    volumes:
      - ./config:/root/seata-config
    environment:
      - SEATA_PORT=8091
      - SEATA_IP=192.168.1.2
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry
